workflows:
  android-build:
    name: Lensora Studio Android Build
    max_build_duration: 45
    instance_type: mac_mini_m1

    environment:
      java: 17

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Grant permissions
        script: |
          chmod +x gradlew

      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug

      - name: Build Release APK
        script: |
          ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/**/*.apk
